import type {
  ChannelPreview,
  DownloadItem,
  PlaylistPreview,
  Settings,
  Subscription,
  VideoPreview,
} from "./types"

export const THUMBNAILS = {
  tech: "/thumbnails/tech.png",
  coding: "/thumbnails/coding.png",
  music: "/thumbnails/music.png",
  travel: "/thumbnails/travel.png",
  gaming: "/thumbnails/gaming.png",
  cooking: "/thumbnails/cooking.png",
}

const thumbList = Object.values(THUMBNAILS)
export function randomThumb(seed = 0) {
  return thumbList[seed % thumbList.length]
}

export const mockDownloads: DownloadItem[] = [
  {
    id: "d1",
    title: "Construire une app Next.js 16 de A à Z — le guide complet",
    thumbnail: THUMBNAILS.coding,
    sourceUrl: "https://youtube.com/watch?v=abc123",
    source: "youtube",
    channel: "Tech Forge",
    quality: "1080p",
    format: "MP4",
    status: "downloading",
    progress: 64,
    speed: "8.4 MB/s",
    eta: "01:12",
    sizeDownloaded: "612 MB",
    sizeTotal: "956 MB",
    createdAt: "2026-06-16T09:12:00Z",
  },
  {
    id: "d2",
    title: "Lofi beats pour coder — session studio 2 heures",
    thumbnail: THUMBNAILS.music,
    sourceUrl: "https://youtube.com/watch?v=def456",
    source: "youtube",
    channel: "Chill Codes",
    quality: "Audio seul",
    format: "MP3",
    status: "converting",
    progress: 92,
    speed: "—",
    eta: "00:08",
    sizeDownloaded: "188 MB",
    sizeTotal: "188 MB",
    createdAt: "2026-06-16T09:05:00Z",
  },
  {
    id: "d3",
    title: "Test du nouveau flagship — vaut-il vraiment son prix ?",
    thumbnail: THUMBNAILS.tech,
    sourceUrl: "https://vimeo.com/987654",
    source: "vimeo",
    channel: "Tech Forge",
    quality: "720p",
    format: "MP4",
    status: "queued",
    progress: 0,
    sizeTotal: "420 MB",
    createdAt: "2026-06-16T09:20:00Z",
  },
  {
    id: "d4",
    title: "Roadtrip dans les Alpes — 4K cinematic",
    thumbnail: THUMBNAILS.travel,
    sourceUrl: "https://youtube.com/watch?v=ghi789",
    source: "youtube",
    channel: "Wander Lens",
    quality: "1080p",
    format: "MKV",
    status: "paused",
    progress: 38,
    speed: "—",
    eta: "—",
    sizeDownloaded: "740 MB",
    sizeTotal: "1.9 GB",
    createdAt: "2026-06-16T08:50:00Z",
  },
  {
    id: "d5",
    title: "Speedrun any% — nouveau record du monde commenté",
    thumbnail: THUMBNAILS.gaming,
    sourceUrl: "https://twitch.tv/videos/112233",
    source: "twitch",
    channel: "Pixel Rush",
    quality: "1080p",
    format: "MP4",
    status: "failed",
    progress: 17,
    error:
      "HTTP Error 403: Forbidden — le serveur a refusé la connexion. Vérifiez vos cookies ou réessayez avec un proxy.",
    sizeDownloaded: "210 MB",
    sizeTotal: "1.2 GB",
    createdAt: "2026-06-16T08:30:00Z",
  },
  {
    id: "d6",
    title: "Recette pâtes fraîches maison en 20 minutes",
    thumbnail: THUMBNAILS.cooking,
    sourceUrl: "https://youtube.com/watch?v=jkl012",
    source: "youtube",
    channel: "Cuisine Minute",
    quality: "1080p",
    format: "MP4",
    status: "completed",
    progress: 100,
    sizeDownloaded: "486 MB",
    sizeTotal: "486 MB",
    createdAt: "2026-06-15T20:14:00Z",
    filePath: "/Downloads/Cuisine Minute/2026-06-15 - Recette pates fraiches.mp4",
  },
  {
    id: "d7",
    title: "Les bases du machine learning expliquées simplement",
    thumbnail: THUMBNAILS.coding,
    sourceUrl: "https://youtube.com/watch?v=mno345",
    source: "youtube",
    channel: "Tech Forge",
    quality: "720p",
    format: "MP4",
    status: "completed",
    progress: 100,
    sizeDownloaded: "342 MB",
    sizeTotal: "342 MB",
    createdAt: "2026-06-15T18:02:00Z",
    filePath: "/Downloads/Tech Forge/2026-06-15 - Bases du machine learning.mp4",
  },
  {
    id: "d8",
    title: "Album complet — Midnight Drive (Full Album)",
    thumbnail: THUMBNAILS.music,
    sourceUrl: "https://youtube.com/watch?v=pqr678",
    source: "youtube",
    channel: "Chill Codes",
    quality: "Audio seul",
    format: "M4A",
    status: "completed",
    progress: 100,
    sizeDownloaded: "96 MB",
    sizeTotal: "96 MB",
    createdAt: "2026-06-14T22:40:00Z",
    filePath: "/Downloads/Chill Codes/2026-06-14 - Midnight Drive.m4a",
  },
  {
    id: "d9",
    title: "Documentaire — la vie secrète des océans",
    thumbnail: THUMBNAILS.travel,
    sourceUrl: "https://dailymotion.com/video/x99zz",
    source: "dailymotion",
    channel: "Wander Lens",
    quality: "480p",
    format: "MP4",
    status: "failed",
    progress: 0,
    error: "Unable to extract video data — format non supporté par l'extracteur.",
    sizeTotal: "—",
    createdAt: "2026-06-14T15:10:00Z",
  },
]

export const mockChannel: ChannelPreview = {
  id: "ch1",
  name: "Tech Forge",
  avatar: "/avatars/channel1.png",
  url: "https://youtube.com/@techforge",
  subscribers: "1,24 M",
  videoCount: 342,
  description:
    "Reviews tech, tutoriels développement et deep-dives hardware chaque semaine.",
}

export const mockPlaylist: PlaylistPreview = {
  id: "pl1",
  title: "Cours complet Next.js & React",
  thumbnail: THUMBNAILS.coding,
  url: "https://youtube.com/playlist?list=PLxyz",
  channel: "Tech Forge",
  videoCount: 24,
}

export const mockVideoPreview: VideoPreview = {
  id: "v1",
  title: "Construire une app Next.js 16 de A à Z — le guide complet",
  thumbnail: THUMBNAILS.coding,
  duration: "42:18",
  channel: "Tech Forge",
  source: "youtube",
  views: "284 K vues",
  uploaded: "il y a 3 jours",
}

const videoTitles = [
  "Next.js 16 : tout ce qui change pour les devs",
  "J'ai testé 10 frameworks CSS — le verdict",
  "Construire un SaaS en un week-end",
  "TypeScript avancé : les patterns que personne n'explique",
  "Optimiser les performances React en 2026",
  "Déployer sur Vercel comme un pro",
  "Les erreurs de débutant à éviter en backend",
  "Architecture propre pour grandes applications",
  "Introduction aux Server Components",
  "Animer une interface avec fluidité",
  "Sécuriser son API : le guide essentiel",
  "Bases de données : SQL vs NoSQL en pratique",
]

export function makeChannelVideos(): VideoPreview[] {
  return videoTitles.map((title, i) => ({
    id: `cv${i}`,
    title,
    thumbnail: randomThumb(i),
    duration: i % 5 === 0 ? "0:48" : `${8 + i}:${(i * 7) % 60}`.padEnd(5, "0"),
    channel: "Tech Forge",
    source: "youtube",
    views: `${(i + 1) * 37} K vues`,
    uploaded: `il y a ${i + 1} jour${i > 0 ? "s" : ""}`,
    isShort: i % 5 === 0,
    isLive: i === 3,
  }))
}

export const mockSubscriptions: Subscription[] = [
  {
    id: "s1",
    type: "channel",
    name: "Tech Forge",
    avatar: "/avatars/channel1.png",
    url: "https://youtube.com/@techforge",
    checkIntervalHours: 6,
    active: true,
    lastChecked: "2026-06-16T07:00:00Z",
    filters: {
      minDuration: 5,
      maxDuration: 90,
      excludeShorts: true,
      excludeLives: true,
      includeKeywords: ["tutoriel", "guide"],
      excludeKeywords: ["live", "réaction"],
      keepLastN: 20,
    },
    defaultQuality: "1080p",
    defaultFormat: "MP4",
  },
  {
    id: "s2",
    type: "playlist",
    name: "Cours complet Next.js & React",
    avatar: "/avatars/channel2.png",
    url: "https://youtube.com/playlist?list=PLxyz",
    checkIntervalHours: 24,
    active: true,
    lastChecked: "2026-06-15T22:00:00Z",
    filters: {
      excludeShorts: false,
      excludeLives: false,
      includeKeywords: [],
      excludeKeywords: [],
    },
    defaultQuality: "720p",
    defaultFormat: "MP4",
  },
  {
    id: "s3",
    type: "channel",
    name: "Chill Codes",
    avatar: "/avatars/channel3.png",
    url: "https://youtube.com/@chillcodes",
    checkIntervalHours: 12,
    active: false,
    lastChecked: "2026-06-13T10:00:00Z",
    filters: {
      excludeShorts: true,
      excludeLives: true,
      includeKeywords: [],
      excludeKeywords: ["short"],
      keepLastN: 10,
    },
    defaultQuality: "Audio seul",
    defaultFormat: "MP3",
  },
]

export const defaultSettings: Settings = {
  downloadDir: "/Users/moi/Downloads/Vidéos",
  defaultQuality: "1080p",
  defaultFormat: "MP4",
  filenameTemplate: "{chaine}/{date} - {titre}",
  organizeBySubfolder: true,
  subtitles: { enabled: true, languages: ["fr", "en"], embed: false },
  embedMetadata: true,
  embedThumbnail: true,
  embedChapters: true,
  maxConcurrent: 3,
  bandwidthLimit: "",
  proxy: "",
  sponsorBlock: true,
  sponsorBlockMode: "skip",
  cookiesImport: false,
  downloadArchive: true,
  theme: "dark",
}
